export const REMOVE_EDITOR_CONTENT_ITEM = "REMOVE_EDITOR_CONTENT_ITEM";
export const CHANGE_EDITOR_CONTENT_ITEM = "CHANGE_EDITOR_CONTENT_ITEM";
export const COPY_EDITOR_CONTENT_ITEM = "COPY_EDITOR_CONTENT_ITEM";
